### ISSUE TITLE
Unemployed Problem

### ISSUE THREAD

**Issue by DiabolicAngeL** [Project-Sloth/ps-multijob#10]
Hello,

1. When I delete a job the unemployed job doesn't get added to civilian jobs.
2. Also, when a job gets removed it doesn't really remove it. It removes it from the menu only. When using /job I still have the job. (Tried with police job)
3. Can you make it so the unemployed status can't be deleted but replaced with the first job that get's added and then to be back when the job gets deleted?

Framework: QBcore

Thanks!

**Comment by S1lentcodes** [comment]
1. Unemployed will not show up as a job. When I delete a job, I get added to another civilian job (just checked it work).
2. I have tried /removejob and it does in fact remove me from the police job and auto places me a civilian job. So make sure you have the latest version of this code because it does work.
3. When you dont have it job it is currently under job: civilian and grade: freelancer.

**Comment by DiabolicAngeL** [comment]
> In the config unemployed is an ignored job, have you tried enabling the job?
> 
> 1. Unemployed will not show up as a job. When I delete a job, I get added to another civilian job (just checked it work).
> 2. I have tried /removejob and it does in fact remove me from the police job and auto places me a civilian job. So make sure you have the latest version of this code because it does work.
> 3. When you dont have it job it is currently under job: civilian and grade: freelancer.

Hello, I got a clip so you can see what i mean
https://streamable.com/20xjqe

**Comment by S1lentcodes** [comment]
Gotcha, I was able to repo the problem when there were no other jobs besides one whitelist job and leaving.

**Comment by S1lentcodes** [comment]
Ok should be fixed, please pull from latest

**Comment by DiabolicAngeL** [comment]
> Ok should be fixed, please pull from latest

Hello it works now thanks a lot!

Something else now.
When you delete a job and change to civilian tab right after it shows a "job" as civilian.
Now, if you close the menu and open it again it dissappears.
I don't  know if this is how it works but a suggestion.

Wouldn't be better for the civilian job to stay till you get a job, no matter if it's whitelisted or not and also remove the delete button from the civilian "job" since it doesn't have to be deletes so the users can see they do not have a job or maybe they got fired.

Hope you understand what I mean. Thanks a lot!
![Screenshot 2022-12-21 070230](https://user-images.githubusercontent.com/68332732/208825604-d6ff39dd-335b-4978-9203-e5eea70994b8.jpg)

**Comment by MonkeyWhisper** [comment]
> 

No because civilian is not a permanent job from the core, it's unemployed.
