### ISSUE TITLE
[Suggestion] Bypass Job limit for admins

### ISSUE THREAD

**Issue by Nanorithm** [Project-Sloth/ps-multijob#13]
It would be awesome if it was possible to have a config option where admins can bypass the job limit but still keep the limit for others. Would help out for admins that have to constantly swap jobs for various reasons

**Comment by MonkeyWhisper** [comment]
> It would be awesome if it was possible to have a config option where admins can bypass the job limit but still keep the limit for others. Would help out for admins that have to constantly swap jobs for various reasons

https://github.com/Project-Sloth/ps-multijob/pull/14
