### ISSUE TITLE
SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @ps-multijob/server/sv_main.lua:137: attempt to index a nil value (field 'Jobs')

### ISSUE THREAD

**Issue by CoZmoTheGod** [Project-Sloth/ps-multijob#16]
Some users are able to use the multijob menu just fine and some can't, it will just place a cursor on screen like the menu is open and this error is thrown in console.

[      script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:741: SCRIPT ERROR: @ps-multijob/server/sv_main.lua:137: attempt to index a nil value (field 'Jobs')
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > runMicrotasks (<anonymous>:0)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 
[      script:qb-core] > TriggerCallback (@qb-core/server/functions.lua:250)
[      script:qb-core] > handler (@qb-core/server/events.lua:116)
[      script:qb-core] > <unknown> (@oxmysql/dist/build.js:22252)
[      script:qb-core] > runMicrotasks (<anonymous>:0)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by gringoDiaz** [comment]
if you are using qbox recipe then replace gradeLabel = QBCore.Shared.Jobs[job].grades[tostring(grade)].name, with gradeLabel = QBCore.Shared.Jobs[job].grades[grade].name,
