### ISSUE TITLE
No scroll bar after 5 jobs

### ISSUE THREAD

**Issue by MonkeyWhisper** [Project-Sloth/ps-multijob#3]
After 5 added jobs, no scroll bar

**Comment by GhostLegionRP** [comment]
https://github.com/Project-Sloth/ps-multijob/pull/5
should fix it =)

**Comment by QBLes** [comment]
i had the same issue, best i could do so it wasnt out of place was change the css for the job section to make them all smaller.. the fix above was little odd because it scrolled the hole thing not just the job section..

**Comment by xFutte** [comment]
I'll take a look at it.

**Comment by MonkeyWhisper** [comment]
Already fixed on dev branch, no worries Futte
