### ISSUE TITLE
SCRIPT ERROR: @ps-multijob/server/sv_main.lua:137

### ISSUE THREAD

**Issue by djkriss0804** [Project-Sloth/ps-multijob#30]
Hello I have a problem with ps-multijob I am getting an error:

[ script:qb-core] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:739: SCRIPT ERROR: @ps-multijob/server/sv_main.lua:137: attempt to index a nil value (field '?')

My premium scripts: 
![MasterRPaddonsV2](https://github.com/Project-Sloth/ps-multijob/assets/104799683/250b7605-2726-4e3f-a80d-aa7c0a286d15)

**Comment by xFutte** [comment]
Ask for help in Discord.
