### ISSUE TITLE
Script has to be restarted after server restart in order for it to work

### ISSUE THREAD

**Issue by spanxurazz** [Project-Sloth/ps-multijob#33]
I am experiencing an issue where after my server restarts, the ps-multijobs script wont show up when you press your j key. It pulls up your mouse icon like it is there but the menu does not open. But then I go into my resources on txadmin and restart the resource and it works just fine. How do I fix this issue?

**Comment by fransdg** [comment]
> I am experiencing an issue where after my server restarts, the ps-multijobs script wont show up when you press your j key. It pulls up your mouse icon like it is there but the menu does not open. But then I go into my resources on txadmin and restart the resource and it works just fine. How do I fix this issue?

do you have solved it?

**Comment by rstreetz** [comment]
What is the fix for this I have the same issue
