### ISSUE TITLE
Sometimes when people switch jobs, it resets their job rank to zero

### ISSUE THREAD

**Issue by SmithyDevelopment** [Project-Sloth/ps-multijob#39]
I havent been able to replicate this on my characters, it works for me fine, but some players report that the job, eg police job.. 
will reset them back to recruit, grade zero, after doing another job and switching back.
Im sorry its not more information but we havent been able to re create the issue, its just from a few bug reports.

**Comment by NAUGHTYDEVlL** [comment]
This is happening to me as well, with all jobs, switching between jobs demotes you to the lowest rank

**Comment by TankinTom** [comment]
@SmithyDevelopment Did you ever get a fix for this?
