### ISSUE TITLE
Whitelisted Jobs Not Showing

### ISSUE THREAD

**Issue by TheCrypticOG** [Project-Sloth/ps-multijob#4]
All my normal jobs are showing however when I gave myself the whitelisted job "police" it is not showing up under the whitelisted section.  I logged out and back in to see if it would fix it and it did not

![FiveM_b2699_GTAProcess_qOgFOh7iRl](https://user-images.githubusercontent.com/98983638/206017948-04b6d33f-0b59-490c-be72-90b9c2727ab4.jpg)
![FiveM_b2699_GTAProcess_pBjUXyMtT5](https://user-images.githubusercontent.com/98983638/206018052-28c063e1-98b3-4be3-a0a1-de78082383a7.png)

**Comment by MonkeyWhisper** [comment]
Cannot duplicate. Works as intended.
