### ISSUE TITLE
What this means? And why?

### ISSUE THREAD

**Issue by Gameadictive** [Project-Sloth/ps-multijob#48]
![imagen_2024-05-15_221133401](https://github.com/Project-Sloth/ps-multijob/assets/65845786/cb4933be-0c47-4d9b-9a33-4de22e7ea9c3)

**Comment by MonkeyWhisper** [comment]
Fix it yourself.

**Comment by Gameadictive** [comment]
> Fix it yourself.

Are u not giving support anymore? Unable to fix ur own errors?

**Comment by MonkeyWhisper** [comment]
> > Fix it yourself.
> 
> Are u not giving support anymore? Unable to fix ur own errors?

I can fix it. :) 

Unlike you asking for support on a simple solution. 

Go get better at coding, loser.
