### ISSUE TITLE
Odd behavior when switching between job categories

### ISSUE THREAD

**Issue by pnacamuli17** [Project-Sloth/ps-multijob#7]
Seeing some weird behavior when switching between the civilian and whitelisted job categories.  If you close a category with a job populated and quickly click on the other category before it has transitioned completely off the screen it appears that the job will show up in the other category.  

Video demonstrating this behavior is attached.  Issue can be seen at about 0:15.

In this case of the video attached, I had the Vanilla Unicorn job and when closing the civilian category and quickly clicking on the whitelisted category, it would show up in the whitelisted jobs list even though it was not configured as a whitelisted job.

https://user-images.githubusercontent.com/44005002/206237331-212d9562-3abf-47b0-bed9-2bfa7793a312.mp4

**Comment by S1lentcodes** [comment]
Thank you for your report! I have pushed the fix to the main branch. Let me know if that resolved the issue for you!
