### ISSUE TITLE
[BUG] Setting Jobs and promotions not updating in PS-Multijob

### ISSUE THREAD

**Issue by NikoClapz19** [Project-Sloth/ps-multijob#9]
When promoting through the QB-management Boss Menu ranks are not updating in the PS-Multijob menu

**Comment by S1lentcodes** [comment]
Thank you for the report will look into this tonight

**Comment by S1lentcodes** [comment]
I have this in the code, are you using the latest code?

**Comment by S1lentcodes** [comment]
I have fixed this issue please download latest code.
